# Generated by Django 5.2.9 on 2025-12-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(help_text='Internal Company ID', max_length=50, unique=True)),
                ('biometric_id', models.IntegerField(help_text='ID on the ZK Device', unique=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Custom working hours for this employee (leave blank to use default)', max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_working_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Default working hours per day', max_digits=4)),
                ('lunch_start_time', models.TimeField(default='13:00:00', help_text='Lunch break start time (HH:MM:SS)')),
                ('lunch_end_time', models.TimeField(default='13:30:00', help_text='Lunch break end time (HH:MM:SS)')),
                ('exclude_lunch_from_hours', models.BooleanField(default=True, help_text='Exclude lunch break from total working hours calculation')),
            ],
            options={
                'verbose_name': 'Work Settings',
                'verbose_name_plural': 'Work Settings',
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_check_in', models.TimeField(blank=True, null=True)),
                ('last_check_out', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime hours for this day', max_digits=5)),
                ('is_overtime', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='attendance.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.IntegerField(default=0, help_text='Device Status Code (0=Check-In, 1=Check-Out, etc.)')),
                ('verification_mode', models.IntegerField(default=1, help_text='Verification Mode')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='attendance.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('employee', 'timestamp')},
            },
        ),
    ]
