# Generated by Django 5.2.9 on 2025-12-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('shift_type', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('GENERAL', 'General/Flexible')], default='DAY', max_length=10)),
                ('start_time', models.TimeField(help_text='Shift start time (HH:MM)')),
                ('end_time', models.TimeField(help_text='Shift end time (HH:MM)')),
                ('working_hours', models.DecimalField(decimal_places=2, help_text='Expected working hours for this shift', max_digits=4)),
                ('break_start_time', models.TimeField(blank=True, help_text='Break start time (leave blank for no break)', null=True)),
                ('break_end_time', models.TimeField(blank=True, help_text='Break end time', null=True)),
                ('exclude_break', models.BooleanField(default=True, help_text='Exclude break time from working hours calculation')),
                ('night_shift_allowance', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra pay percentage for night shift (e.g., 20.00 for 20%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='day_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hours worked during day period', max_digits=5),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hours worked during night period', max_digits=5),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='night_shift_allowance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated night shift allowance amount', max_digits=6),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='night_end_time',
            field=models.TimeField(default='06:00:00', help_text='Night period end time'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='night_start_time',
            field=models.TimeField(default='22:00:00', help_text='Night period start time (for night hours calculation)'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(help_text='Calendar date (for day shifts) or shift start date (for night shifts)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom working hours for this employee (leave blank to use shift/default)', max_digits=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='The shift this summary belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Assigned shift (leave blank for auto-detection)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('employee', 'date', 'shift')},
        ),
    ]
