# Generated by Django 5.2.9 on 2025-12-19 11:34

from django.db import migrations


def create_default_shifts(apps, schema_editor):
    """Create default day, night, and general shifts"""
    Shift = apps.get_model('attendance', 'Shift')
    
    # Day Shift (9 AM - 6 PM)
    Shift.objects.get_or_create(
        name='Day Shift',
        defaults={
            'shift_type': 'DAY',
            'start_time': '09:00:00',
            'end_time': '18:00:00',
            'working_hours': 8.0,
            'break_start_time': '13:00:00',
            'break_end_time': '13:30:00',
            'exclude_break': True,
            'night_shift_allowance': 0.0,
            'is_active': True
        }
    )
    
    # Night Shift (10 PM - 6 AM)
    Shift.objects.get_or_create(
        name='Night Shift',
        defaults={
            'shift_type': 'NIGHT',
            'start_time': '22:00:00',
            'end_time': '06:00:00',
            'working_hours': 8.0,
            'break_start_time': '02:00:00',
            'break_end_time': '02:30:00',
            'exclude_break': True,
            'night_shift_allowance': 20.0,  # 20% extra pay
            'is_active': True
        }
    )
    
    # General/Flexible Shift
    Shift.objects.get_or_create(
        name='General',
        defaults={
            'shift_type': 'GENERAL',
            'start_time': '00:00:00',
            'end_time': '23:59:59',
            'working_hours': 8.0,
            'break_start_time': None,
            'break_end_time': None,
            'exclude_break': False,
            'night_shift_allowance': 0.0,
            'is_active': True
        }
    )


def reverse_default_shifts(apps, schema_editor):
    """Remove default shifts"""
    Shift = apps.get_model('attendance', 'Shift')
    Shift.objects.filter(name__in=['Day Shift', 'Night Shift', 'General']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_shift_dailysummary_day_hours_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_shifts, reverse_default_shifts),
    ]
