# Generated by Django 5.2.9 on 2025-12-19 15:21

from django.db import migrations
from datetime import date


def set_default_working_hours(apps, schema_editor):
    """Set default working hours for all employees"""
    Employee = apps.get_model('attendance', 'Employee')
    
    # Update all employees without working hours to 8.0
    employees_updated = Employee.objects.filter(working_hours__isnull=True).update(working_hours=8.0)
    print(f"✓ Set working_hours=8.0 for {employees_updated} employees")


def clean_old_data(apps, schema_editor):
    """Remove all data before Dec 19, 2025"""
    AttendanceLog = apps.get_model('attendance', 'AttendanceLog')
    DailySummary = apps.get_model('attendance', 'DailySummary')
    
    cutoff_date = date(2025, 12, 19)
    
    # Delete old attendance logs
    old_logs_count, _ = AttendanceLog.objects.filter(timestamp__date__lt=cutoff_date).delete()
    print(f"✓ Deleted {old_logs_count} attendance logs before {cutoff_date}")
    
    # Delete old daily summaries
    old_summaries_count, _ = DailySummary.objects.filter(date__lt=cutoff_date).delete()
    print(f"✓ Deleted {old_summaries_count} daily summaries before {cutoff_date}")


def reverse_working_hours(apps, schema_editor):
    """Reverse operation - set working hours back to None"""
    Employee = apps.get_model('attendance', 'Employee')
    Employee.objects.all().update(working_hours=None)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_create_default_shifts'),
    ]

    operations = [
        migrations.RunPython(set_default_working_hours, reverse_working_hours),
        migrations.RunPython(clean_old_data, migrations.RunPython.noop),
    ]
