# Generated by Django 5.2.9 on 2025-12-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_set_default_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=8.0, help_text='Custom working hours for this employee (defaults to 8.0 hours)', max_digits=4, null=True),
        ),
    ]
