# Generated by Django 6.0 on 2025-12-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_employee_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(default='192.168.2.66', help_text='IP address of the ZK biometric device', max_length=15)),
                ('device_port', models.IntegerField(default=4370, help_text='Port number for device connection')),
                ('timeout', models.IntegerField(default=60, help_text='Connection timeout in seconds')),
                ('password', models.IntegerField(default=0, help_text='Device password (usually 0)')),
                ('force_udp', models.BooleanField(default=True, help_text='Force UDP connection')),
                ('ommit_ping', models.BooleanField(default=True, help_text='Skip initial ping check')),
            ],
            options={
                'verbose_name': 'Device Settings',
                'verbose_name_plural': 'Device Settings',
            },
        ),
    ]
