# Generated by Django 6.0 on 2025-12-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_populate_device_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this log was last manually edited', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='edited_by',
            field=models.CharField(blank=True, help_text='Username of the person who edited this log', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_manually_edited',
            field=models.BooleanField(default=False, help_text='If True, this log was manually edited and should not be overridden by sync'),
        ),
    ]
