# Generated by Django 5.2.9 on 2025-12-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_add_manual_edit_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='evening_end_time',
            field=models.TimeField(default='21:30:00', help_text='Evening peak sync end time'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='evening_interval_mins',
            field=models.IntegerField(default=5, help_text='Evening peak sync interval in minutes'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='evening_start_time',
            field=models.TimeField(default='20:00:00', help_text='Evening peak sync start time'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='morning_end_time',
            field=models.TimeField(default='10:00:00', help_text='Morning peak sync end time'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='morning_interval_mins',
            field=models.IntegerField(default=5, help_text='Morning peak sync interval in minutes'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='morning_start_time',
            field=models.TimeField(default='08:45:00', help_text='Morning peak sync start time'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='sync_interval_mins',
            field=models.IntegerField(default=30, help_text='Standard sync interval in minutes'),
        ),
    ]
